CC=gcc
CFLAGS=-g -pedantic -std=c99 -Wall -Wextra

all: exc1 exc2 exc3 exc5

exc1: exc1.c
	$(CC) -o exc1 exc1.c $(CFLAGS)

exc2: exc2.c
	$(CC) -o exc2 exc2.c $(CFLAGS)

exc3: exc3.c
	$(CC) -o exc3 exc3.c $(CFLAGS)

exc5: exc5.c
	$(CC) -o exc5 exc5.c $(CFLAGS)

clean:
	rm exc1 exc2 exc3 exc5